version: '3'
x-airflow-common:
  &airflow-common
  image: apache/airflow:2.0.0
  container_name: sp3_airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres_airflow:5432/airflow
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
    - ./airflow-data/airflow.cfg:/opt/airlfow/airflow.cfg
  depends_on:
    - postgres_airflow

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: sp3_code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/home #optional
    volumes:
      - ../:/home
    ports:
      - 10001:8443
    restart: unless-stopped
    networks:
      - gcp
  postgres_airflow:
    container_name: sp3_postgres
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    # networks:
    #   - gcp

  airflow-init:
    << : *airflow-common
    container_name: sp3_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init &&
        airflow users create
          --role Admin
          --username dataengineer
          --password dataengineer
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow )
    restart: on-failure

  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 10002:8080
    container_name: sp3_airflow_webserver
    restart: always
    # networks:
    #   - gcp

  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: sp3_airflow_scheduler
    restart: always
    # networks:
    #   - gcp

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: sp3_zookeeper
    ports:
     - "2181:2181"
    networks:
      - gcp
  kafka:
    container_name: sp3_kafka
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gcp
  
  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    restart: always
    ports:
      - "10003:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    networks:
      - gcp

networks:
  gcp:
    driver: bridge